apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  token: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVFITFJHS01OR05aVlc3R1gKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gemZjNzdlbmdmNVRhVFlzbUliL0NiKzVCZ1hLaC9oRkIwNGVrTkw2Zwo=