apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 80
    targetPort: 8100
    protocol: TCP
  selector:
    run: frontend
  type: LoadBalancer