# CircleCI configuration file
version: 2.1

jobs:
  reverseproxy:
    docker:
    - image: cimg/base:stable
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
        - run: docker --version # print the version for logging
        - run: docker build -t udagram-reverseproxy ./udagram-reverseproxy
        - run: docker tag udagram-reverseproxy rgues2021/udagram-reverseproxy:v1
        - run: docker push rgues2021/udagram-reverseproxy:v1
      
  backend-user:
    docker:
    - image: cimg/base:stable
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
        - run: docker build -t udagram-api-user ./udagram-api-user
        - run: docker tag udagram-api-user rgues2021/udagram-api-user:v1
        - run: docker push rgues2021/udagram-api-user:v1

  backend-feed:
    docker:
    - image: cimg/base:stable
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps: 
      - run: docker build -t udagram-api-feed ./udagram-api-feed
      - run: docker tag udagram-api-feed rgues2021/udagram-api-feed:v1
      - run: docker push rgues2021/udagram-api-feed:v1

  frontend:
    docker:
    - image: cimg/base:stable
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:   
      - run: docker build -t udagram-frontend ./udagram-frontend
      - run: docker tag udagram-frontend rgues2021/udagram-frontend:v1
      - run: docker push rgues2021/udagram-frontend:v1

workflows:
  # Name of workflow
  backend_and_frontend:
    # List of jobs that will run
    jobs:
      - reverseproxy
      - backend-user
      - backend-feed
      - frontend