# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    - image: cimg/base:stable
      auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
        - checkout
        - setup_remote_docker
        - run: 
            name: version
            command: |
               docker --version 
        - run: 
            name: build reverse proxy image
            command: |
              docker build -t udagram-reverseproxy ./udagram-reverseproxy
        - deploy: 
            name: deploy reverse proxy
            command : 
              docker tag udagram-reverseproxy rgues2021/udagram-reverseproxy:v1
              docker push rgues2021/udagram-reverseproxy:v1

        - run: 
            name: build user service image
            command: |
              docker build -t udagram-api-user ./udagram-api-user
        - deploy: 
            name: deploy reverse proxy
            command : 
              docker tag udagram-api-user rgues2021/udagram-api-user:v1
              docker push rgues2021/udagram-api-user:v1
     
        - run: 
            name: build feed service image
            command: |
              docker build -t udagram-api-feed ./udagram-api-feed
        - deploy: 
            name: deploy feed service image
            command : 
              docker tag udagram-api-feed rgues2021/udagram-api-feed:v1
              docker push rgues2021/udagram-api-feed:v1

        - run: 
            name: build frontend app image
            command: |
              docker build -t udagram-frontend ./udagram-frontend
        - deploy: 
            name: deploy frontend app image
            command : 
              docker tag udagram-frontend rgues2021/udagram-frontend:v1
              docker push rgues2021/udagram-frontend:v1
